aligned_msa_filename: wt_3vdh_aln.fasta
reweighting_threshold: 0.8
dataset_dir: sequence_sets
working_dir: working
model_name: model_1000_15
hidden_layer_size: 1000
latent_layer_size: 15
activation_function: sigmoid
learning_rate: .001
epochs: 1000
batch_size: 128
device: auto
