aligned_msa_filename: cmx_aligned_blank_90.fasta
reweighting_threshold: 0.8

# These directories need to be specified relative to the main directory
dataset_dir: sequence_sets
working_dir: working

model_name: model

learning_rate: .001
epochs: 50

# batch_size of -1 means the entire dataset
# If our MSA's ever get very large we can look into
# mini-batch and stochastic gradient descent
batch_size: -1

device: auto # possible options are cpu, cuda, auto
