aligned_msa_filename: cmx_aligned_blank_90.fasta
reweighting_threshold: 0.8

# These directories need to be specified relative to the main directory
dataset_dir: sequence_sets
working_dir: working

convert_unknown_aa_to_gap: True

model_name: cmx_dca
dca_regularization: l2

dca_params_filename: cmx_dca_params.pkl

learning_rate: .001
epochs: 50

device: auto # possible options are cpu, cuda, auto
