aligned_msa_filename: cmx_aligned_blank_90.fasta
reweighting_threshold: 0.8

# These directories need to be specified relative to the main directory
dataset_dir: sequence_sets
working_dir: working

# Do not put spaces or other special characters into model_name below If the
# model_name is model then the following files will be saved in the working
# directory
#  1. model.pt (saved pytorch model)
#  2. model_loss.pkl (saved loss function)
#  3. model_loss.png (loss function graphed)
#  4. model_latent.pkl (saved latent space)

model_name: model2d

hidden_layer_size: 400
# latent_layer_size must be 2 to make a 2d plot of the latent space
latent_layer_size: 2
activation_function: sigmoid
learning_rate: .001
epochs: 5
batch_size: 128
device: auto


# Plotting options
foreground_sequences_filename: cmx_foreground.fasta
foreground_sequences_output_filename: cmx_latent.png
