# submit file for VAEs in Pytorch

# Must set the universe to Docker
universe = docker
docker_image = romerolab/chtc:pytorch-nvidia-v16Dec19

# set the log, error and output files 
log = logs/pytorch_reweighting_$(Process).log.txt
error = logs/pytorch_reweighting_$(Process).err.txt
output = logs/pytorch_reweighting_$(Process).out.txt

# set the executable to run
executable = pytorch_reweighting.sh
arguments = -t $(threshold) -i ../sequence_sets/$(inputfasta)

# take our python script and data to the compute node
transfer_input_files = staging.tar.gz

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# We require a machine with a modern version of the CUDA driver
Requirements = (Target.CUDADriverVersion >= 10.1)

# We must request 1 CPU in addition to 1 GPU
request_cpus = 1
#request_gpus = 1

# select some memory and disk space
request_memory = 1GB
request_disk = 500MB

# Tell HTCondor to run 1 instances of our job:
queue threshold, inputfasta from ( 
  0.8, cmx_aligned_blank_90.fasta
)
